export default function getWeatherIconUrl(icon) {
  const url = './img/weather_icons/';
  switch (icon) {
    case 't01d':
    case 't01n':
    case 't02d':
    case 't02n':
    case 't03d':
    case 't03n':
    case 't04d':
    case 't04n':
      return `${url}thunderstorms.svg`;
    case 't05d':
    case 't05n':
      return `${url}hail.svg`;
    case 'd01d':
      return `${url}partly-cloudy-day-drizzle.svg`;
    case 'd01n':
      return `${url}partly-cloudy-night-drizzle.svg`;
    case 'd02d':
    case 'd02n':
    case 'd03d':
    case 'd03n':
      return `${url}drizzle.svg`;
    case 'r01d':
    case 'r01n':
    case 'r02d':
    case 'r02n':
    case 'r03d':
    case 'r03n':
    case 'r04d':
    case 'r04n':
    case 'r06d':
    case 'r06n':
    case 'f01d':
    case 'f01n':
      return `${url}rain.svg`;
    case 'r05d':
      return `${url}partly-cloudy-day-rain.svg`;
    case 'r05n':
      return `${url}partly-cloudy-night-rain.svg`;
    case 'c01d':
      return `${url}clear-day.svg`;
    case 'c01n':
      return `${url}clear-night.svg`;
    case 'c02d':
    case 'c03d':
      return `${url}partly-cloudy-day.svg`;
    case 'c02n':
    case 'c03n':
      return `${url}partly-cloudy-night.svg`;
    case 'c04d':
    case 'c04n':
      return `${url}cloudy.svg`;
    case 's01d':
      return `${url}partly-cloudy-day-hail.svg`;
    case 's01n':
      return `${url}partly-cloudy-day-snow.svg`;
    case 's02d':
    case 's02n':
    case 's03d':
    case 's03n':
    case 's05d':
    case 's05n':
    case 's06d':
    case 's06n':
      return `${url}snow.svg`;
    case 's04d':
      return `${url}partly-cloudy-day-snow.svg`;
    case 's04n':
      return `${url}partly-cloudy-night-hail.svg`;
    case 'a01d':
    case 'a01n':
    case 'a02d':
    case 'a02n':
    case 'a03d':
    case 'a03n':
    case 'a04d':
    case 'a04n':
    case 'a05d':
    case 'a05n':
    case 'a06d':
    case 'a06n':
      return `${url}tornado.svg`;
    default: return null;
  }
}
