const API_KEY_YANDEX_TRANSLATE = 'YOUR_API_KEY_HERE';
const API_KEY_IPINFO = 'YOUR_API_KEY_HERE';
const API_KEY_WEATHERBIT = 'YOUR_API_KEY_HERE';
const API_KEY_GEOCODING = 'YOUR_API_KEY_HERE';
const API_KEY_GOOGLE_MAPS = 'YOUR_API_KEY_HERE';
const API_KEY_UNSPLASH = 'YOUR_API_KEY_HERE';

export {
  API_KEY_YANDEX_TRANSLATE,
  API_KEY_IPINFO,
  API_KEY_WEATHERBIT,
  API_KEY_GEOCODING,
  API_KEY_GOOGLE_MAPS,
  API_KEY_UNSPLASH,
};
